### ISSUE TITLE
RFC support for multiple credentials

### ISSUE THREAD

**Issue by jzijlstra** [Rhinofly/play-basic-authentication-filter#3]
We would like the option to configure multiple different credentials for the basic authentication. For example one for customer use and one for internal use.

**Comment by bluedread** [comment]
Need it. Nagios doesn't handle passwords with exclamation marks and hash-signs well. Escaping doesn't work as it should. We can not monitor the application on acceptance and sandbox now, which we are required to do by the SLA.
